### ISSUE TITLE
Failure syncing subcharts from different registries

### ISSUE THREAD

**Issue by LP0101** [bitnami/charts-syncer#147]
When trying to sync a chart with subcharts in a different remote registry, the sync fails with `no chart name found`.

For example, trying to sync kube-prometheus-stack, it fails copying grafana, which is stored in a separate repo.

Example config:

```
source:
  repo:
    kind: HARBOR
    url: https://prometheus-community.github.io/helm-charts
target:
  repoName: myrepo
  containerRegistry: k8s.container.registry.io
  containerRepository: repository/demo/k8s
  repo:
    kind: OCI
    url: https://<REDACTED>.azurecr.io/helm
    auth:
      username: "<REDACTED>"
      password: "<REDACTED>"
charts:
  - kube-prometheus-stack
```

When running `charts-syncer sync`, I get this:

`0222 16:19:31.882577  101820 index.go:164] unable to load "kube-prometheus-stack-32.2.1" chart: invalid "grafana-6.21.5" chart dependency: getting grafana-6.21.5 from index file: no chart name found`

With the same error for each version it tries to pull. This also happens with other charts with subcharts stored in different registries.
