### ISSUE TITLE
Support add annotations when sync charts

### ISSUE THREAD

**Issue by SSmallMonster** [bitnami/charts-syncer#169]
We now have a scenario for synchronizing chart that uses charts-syncer. 

## Why we need this?
We need to **add some custom classification properties** to the synchronized chart to **indicate different purposes.** 

Our method is to **adds some custom annotations** to the target Chart.yaml, but they are not currently supported in `charts-syncer`.

```
# Annotations in Chart.yaml
apiVersion: The chart API version
...
annotations:
  updateTime: "xxxx"
```

## What we want?
Adding a **chart field** in the [config](https://github.com/bitnami-labs/charts-syncer/blob/master/charts-syncer.yaml) file. This will **greatly help users manage charts during synchronization.**

```
# config.yaml used by charts-syncer
source:
...

target:
  chart:
      annotations:
          updateTime: "xxxx"

charts:
 - xxx
 - xxx
```
